In [11]:
import pandas as pd

In [13]:
mydataset={
    'cars':["bmw", "volvo", "ford"],
    'passings':[3,7,2]
}
myvar=pandas.DataFrame(mydataset)
print(myvar)

    cars  passings
0    bmw         3
1  volvo         7
2   ford         2

In [15]:
#pandas as pd
import pandas as pd
mydataset={
    'cars':["bmw", "volvo", "ford"],
    'passings':[3,7,2]
}
myvar=pandas.DataFrame(mydataset)
print(myvar)

    cars  passings
0    bmw         3
1  volvo         7
2   ford         2

In [23]:
#pandas series is like column 
import pandas as pd
a=[1,2,3]
m=pd.Series(a)
print(m)

0    1
1    2
2    3
dtype: int64

In [29]:
import pandas as pd
a=[1,2,3,4,5]
m=pd.Series(a,index=["a","b","c","d","e"])
print(m)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [27]:
print(pd.__version__)

2.2.2

In [35]:
print(a[1])

2

In [39]:
import pandas as pd
cal={"day1":420,"day2":380,"day3":390}
m=pd.Series(cal)
print(m)

day1    420
day2    380
day3    390
dtype: int64

In [45]:
import pandas as pd
cal={"day1":420,"day2":380,"day3":390}
m=pd.Series(cal,index=["day1","day2","d"])
print(m)

day1    420.0
day2    380.0
d         NaN
dtype: float64

In [ ]:
import pandas as pd
data={
    "c":[420,380,390],
    "d":[50,40,60]
}
df=pd.DataFrame(data)
print(df)

In [49]:
print(df.loc[0])

c    420
d     50
Name: 0, dtype: int64

In [56]:
print(df.loc[[0,1]])

     c   d
0  420  50
1  380  40

In [58]:
import pandas as pd
df=pd.read_csv('play_tennis.csv')
print(df)

    day   Outlook Temperature Humidity   Windy play
0    D1     Sunny         Hot     High    Weak   No
1    D2     Sunny         Hot     High  Strong   No
2    D3  Overcast         Hot     High    Weak  Yes
3    D4      Rain        Mild     High    Weak  Yes
4    D5      Rain        Cool   Normal    Weak  Yes
5    D6      Rain        Cool   Normal  Strong   No
6    D7  Overcast        Cool   Normal  Strong  Yes
7    D8     Sunny        Mild     High    Weak   No
8    D9     Sunny        Cool   Normal    Weak  Yes
9   D10      Rain        Mild   Normal    Weak  Yes
10  D11     Sunny        Mild   Normal  Strong  Yes
11  D12  Overcast        Mild     High  Strong  Yes
12  D13  Overcast         Hot   Normal    Weak  Yes
13  D14      Rain        Mild     High  Strong   No

In [60]:
df.head()

  day   Outlook Temperature Humidity   Windy play
0  D1     Sunny         Hot     High    Weak   No
1  D2     Sunny         Hot     High  Strong   No
2  D3  Overcast         Hot     High    Weak  Yes
3  D4      Rain        Mild     High    Weak  Yes
4  D5      Rain        Cool   Normal    Weak  Yes

In [62]:
df.drop(0)

    day   Outlook Temperature Humidity   Windy play
1    D2     Sunny         Hot     High  Strong   No
2    D3  Overcast         Hot     High    Weak  Yes
3    D4      Rain        Mild     High    Weak  Yes
4    D5      Rain        Cool   Normal    Weak  Yes
5    D6      Rain        Cool   Normal  Strong   No
6    D7  Overcast        Cool   Normal  Strong  Yes
7    D8     Sunny        Mild     High    Weak   No
8    D9     Sunny        Cool   Normal    Weak  Yes
9   D10      Rain        Mild   Normal    Weak  Yes
10  D11     Sunny        Mild   Normal  Strong  Yes
11  D12  Overcast        Mild     High  Strong  Yes
12  D13  Overcast         Hot   Normal    Weak  Yes
13  D14      Rain        Mild     High  Strong   No

In [64]:
print(df.to_string())#to display total dataset

    day   Outlook Temperature Humidity   Windy play
0    D1     Sunny         Hot     High    Weak   No
1    D2     Sunny         Hot     High  Strong   No
2    D3  Overcast         Hot     High    Weak  Yes
3    D4      Rain        Mild     High    Weak  Yes
4    D5      Rain        Cool   Normal    Weak  Yes
5    D6      Rain        Cool   Normal  Strong   No
6    D7  Overcast        Cool   Normal  Strong  Yes
7    D8     Sunny        Mild     High    Weak   No
8    D9     Sunny        Cool   Normal    Weak  Yes
9   D10      Rain        Mild   Normal    Weak  Yes
10  D11     Sunny        Mild   Normal  Strong  Yes
11  D12  Overcast        Mild     High  Strong  Yes
12  D13  Overcast         Hot   Normal    Weak  Yes
13  D14      Rain        Mild     High  Strong   No